[theme]
primaryColor = "#103662"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F8FC"
textColor = "#212529"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
